version: 1.2
workflows:
   -  name: pepperMarginDvWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/pepper_margin_deepvariant.wdl
   -  name: dipdiffWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/dipdiff.wdl
   -  name: snifflesWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/sniffles.wdl
   -  name: minimapWorkflow
      subclass: WDL
      primaryDescriptorPath: /wdl/workflows/minimap.wdl
   -  name: clair3
      subclass: WDL
      primaryDescriptorPath: /wdl/tasks/clair3.wdl
   -  name: marginPhaseSmall
      subclass: WDL
      primaryDescriptorPath: /wdl/tasks/margin_phase_small.wdl
   -  name: indexVcf
      subclass: WDL
      primaryDescriptorPath: /wdl/tasks/indexVcf.wdl
